apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: khing
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pricefetch
        image: ghcr.io/chinathaip/price-fetcher:a8460cd39bd7b9c9a6676a206114f4379a435bba
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

      - name: catfact
        image: ghcr.io/chinathaip/catfact:ce11ab641700c60a568ae1c7a2cc8dd76b07473c
        imagePullPolicy: Always
        ports:
        - containerPort: 3001