apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: khing
spec:
  ports:
  - name: phpapp
    port: 80
    targetPort: 80
    protocol: TCP

  - name: price-fetch
    port: 3000
    targetPort: 3000
    protocol: TCP
    
  - name: catfact
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: api
  type: LoadBalancer