apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: khing
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  - port: 3001
    targetPort: 3001
  selector:
    app: api
  type: LoadBalancer