apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/chinathaip/testargocd:7cc015172fd402d5bfa92f2b1ac47b6a2e5206a2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port