apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ite-220
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: phpapp
        image: ghcr.io/chinathaip/ite220-cms:b38ec1d48018bb282830b91bf6c81d76e50f3fe4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port